### ISSUE TITLE
Split CSS into a separate file

### ISSUE THREAD

**Issue by Heather-Herbert** [openwebgisystem/OpenWebGIS#3]
The CSS within the Start_OpenWebGIS_en.html / Start_OpenWebGIS_ru.html files is the same and maintainability of the project would be increased by splitting the CSS into its own file.

**Comment by openwebgisystem** [comment]
> The CSS within the Start_OpenWebGIS_en.html / Start_OpenWebGIS_ru.html files is the same and maintainability of the project would be increased by splitting the CSS into its own file.

Thank you,  Heather-Herbert. I agree with your opinion.
